// <auto-generated />
using System;
using FashionStoreIS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FashionStoreIS.Data.Migrations.Analytics
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260405041838_SyncAnalyticsPostgres")]
    partial class SyncAnalyticsPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FashionStoreIS.Models.Analytics.Dim_Customer", b =>
                {
                    b.Property<int>("CustomerSurrogateKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("customersurrogatekey");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerSurrogateKey"));

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("customerid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullname");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("RegionOrCity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("regionorcity");

                    b.HasKey("CustomerSurrogateKey");

                    b.ToTable("dim_customer");
                });

            modelBuilder.Entity("FashionStoreIS.Models.Analytics.Dim_Date", b =>
                {
                    b.Property<int>("DateKey")
                        .HasColumnType("integer")
                        .HasColumnName("datekey");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<int>("Day")
                        .HasColumnType("integer")
                        .HasColumnName("day");

                    b.Property<bool>("IsWeekend")
                        .HasColumnType("boolean")
                        .HasColumnName("isweekend");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<int>("Quarter")
                        .HasColumnType("integer")
                        .HasColumnName("quarter");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("DateKey");

                    b.ToTable("dim_date");
                });

            modelBuilder.Entity("FashionStoreIS.Models.Analytics.Dim_Product", b =>
                {
                    b.Property<int>("ProductSurrogateKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("productsurrogatekey");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductSurrogateKey"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoryname");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("productname");

                    b.Property<int?>("ProductSkuId")
                        .HasColumnType("integer")
                        .HasColumnName("productskuid");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("size");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("validfrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("validto");

                    b.HasKey("ProductSurrogateKey");

                    b.ToTable("dim_product");
                });

            modelBuilder.Entity("FashionStoreIS.Models.Analytics.Fact_Sales", b =>
                {
                    b.Property<int>("FactSalesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("factsalesid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FactSalesId"));

                    b.Property<decimal>("COGS")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cogs");

                    b.Property<int>("CustomerSurrogateKey")
                        .HasColumnType("integer")
                        .HasColumnName("customersurrogatekey");

                    b.Property<int>("DateKey")
                        .HasColumnType("integer")
                        .HasColumnName("datekey");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discountamount");

                    b.Property<decimal>("GrossProfit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("grossprofit");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ordercode");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<int>("ProductSurrogateKey")
                        .HasColumnType("integer")
                        .HasColumnName("productsurrogatekey");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("SalesAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salesamount");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unitprice");

                    b.HasKey("FactSalesId");

                    b.HasIndex("CustomerSurrogateKey");

                    b.HasIndex("DateKey");

                    b.HasIndex("ProductSurrogateKey");

                    b.ToTable("fact_sales");
                });

            modelBuilder.Entity("FashionStoreIS.Models.Analytics.Fact_Sales", b =>
                {
                    b.HasOne("FashionStoreIS.Models.Analytics.Dim_Customer", "DimCustomer")
                        .WithMany()
                        .HasForeignKey("CustomerSurrogateKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionStoreIS.Models.Analytics.Dim_Date", "DimDate")
                        .WithMany()
                        .HasForeignKey("DateKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionStoreIS.Models.Analytics.Dim_Product", "DimProduct")
                        .WithMany()
                        .HasForeignKey("ProductSurrogateKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DimCustomer");

                    b.Navigation("DimDate");

                    b.Navigation("DimProduct");
                });
#pragma warning restore 612, 618
        }
    }
}
