// <auto-generated />
using System;
using FashionStoreIS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace FashionStoreIS.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260325062119_AddProfileFeatures_SQLite_V2")]
    partial class AddProfileFeatures_SQLite_V2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("HILOSEQUENCE");

            modelBuilder.Entity("FashionStoreIS.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(450)")
                        .HasColumnName("ID");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ACCESSFAILEDCOUNT");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("AVATARURL");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("VARCHAR2(2000)")
                        .HasColumnName("CONCURRENCYSTAMP");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATEOFBIRTH");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR2(256)")
                        .HasColumnName("EMAIL");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("EMAILCONFIRMED");

                    b.Property<string>("FullName")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("FULLNAME");

                    b.Property<string>("Gender")
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("GENDER");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("JOINDATE");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("LOCKOUTENABLED");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TIMESTAMP WITH TIME ZONE")
                        .HasColumnName("LOCKOUTEND");

                    b.Property<int>("MembershipPoints")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MEMBERSHIPPOINTS");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR2(256)")
                        .HasColumnName("NORMALIZEDEMAIL");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR2(256)")
                        .HasColumnName("NORMALIZEDUSERNAME");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("VARCHAR2(2000)")
                        .HasColumnName("PASSWORDHASH");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("VARCHAR2(2000)")
                        .HasColumnName("PHONENUMBER");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("PHONENUMBERCONFIRMED");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("VARCHAR2(2000)")
                        .HasColumnName("SECURITYSTAMP");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("TWOFACTORENABLED");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR2(256)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("\"NORMALIZEDUSERNAME\" IS NOT NULL");

                    b.ToTable("ASPNETUSERS", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DISPLAYORDER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("IMAGEURL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("ISACTIVE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("LINKURL");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("POSITION");

                    b.Property<string>("SubTitle")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SUBTITLE");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TITLE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.HasKey("Id");

                    b.ToTable("BANNERS", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("DISPLAYORDER");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("IMAGEURL");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BOOLEAN")
                        .HasDefaultValue(true)
                        .HasColumnName("ISACTIVE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PARENTCATEGORYID");

                    b.Property<string>("Slug")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("SLUG");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("CATEGORIES", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ADDRESS");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATEOFBIRTH");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("FULLNAME");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("JOINDATE");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LOYALTYPOINTS");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("PHONE");

                    b.Property<int>("Tier")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.Property<string>("UserId")
                        .HasColumnType("VARCHAR2(450)")
                        .HasColumnName("USERID");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"USERID\" IS NOT NULL");

                    b.ToTable("CUSTOMERS", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("FULLNAME");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("HIREDATE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("ISACTIVE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PHONE");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("POSITION");

                    b.Property<int>("StoreId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STOREID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("USERID");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("EMPLOYEES", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LASTUPDATED");

                    b.Property<int?>("MaxStockLevel")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MAXSTOCKLEVEL");

                    b.Property<int>("ProductSkuId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUCTSKUID");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITYONHAND");

                    b.Property<int>("ReorderPoint")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("REORDERPOINT");

                    b.Property<int>("StoreId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STOREID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.HasKey("Id");

                    b.HasIndex("ProductSkuId");

                    b.HasIndex("StoreId");

                    b.ToTable("INVENTORIES", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.LoyaltyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CUSTOMERID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<int?>("OrderId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORDERID");

                    b.Property<int>("Points")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("POINTS");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.ToTable("LOYALTYTRANSACTIONS", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("ACTIONURL");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("VARCHAR2(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<bool>("IsRead")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("ISREAD");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("MESSAGE");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TITLE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("VARCHAR2(450)")
                        .HasColumnName("USERID");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("UserId");

                    b.ToTable("NOTIFICATIONS", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ADDRESS");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CUSTOMERID");

                    b.Property<string>("CustomerName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CUSTOMERNAME");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("DISCOUNTAMOUNT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<string>("Note")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOTE");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ORDERCODE");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("PAYMENTMETHOD");

                    b.Property<byte>("PaymentStatus")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("PAYMENTSTATUS");

                    b.Property<string>("Phone")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PHONE");

                    b.Property<int>("PointsEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("POINTSEARNED");

                    b.Property<byte>("Status")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("STATUS");

                    b.Property<int>("StoreId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STOREID");

                    b.Property<long>("SubTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(14,0)")
                        .HasDefaultValue(0L)
                        .HasColumnName("SUBTOTAL");

                    b.Property<long>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(14,0)")
                        .HasDefaultValue(0L)
                        .HasColumnName("TOTALAMOUNT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.Property<string>("UserId")
                        .HasColumnType("VARCHAR2(450)")
                        .HasColumnName("USERID");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VOUCHERID");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("ORDERS", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<decimal>("DiscountPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("DISCOUNTPERCENT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<int>("OrderId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORDERID");

                    b.Property<int?>("ProductId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUCTID");

                    b.Property<int?>("ProductSkuId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUCTSKUID");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITY");

                    b.Property<long>("Subtotal")
                        .HasColumnType("NUMBER(14,0)")
                        .HasColumnName("SUBTOTAL");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("NUMBER(12,0)")
                        .HasColumnName("UNITPRICE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductSkuId");

                    b.ToTable("ORDERDETAILS", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CATEGORYID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("IMAGEURL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("ISACTIVE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NAME");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("PRICE");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("SLUG");

                    b.Property<int>("Stock")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STOCK");

                    b.Property<int>("SupplierId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SUPPLIERID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("PRODUCTS", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DISPLAYORDER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("IMAGEURL");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUCTID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("PRODUCTIMAGES");
                });

            modelBuilder.Entity("FashionStoreIS.Models.ProductSku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("COLOR");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("COSTPRICE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("ISACTIVE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<decimal?>("PriceOverride")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("PRICEOVERRIDE");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUCTID");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("SKU");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("NUMBER(12,2)")
                        .HasColumnName("SELLINGPRICE");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("SIZE");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("SKUCODE");

                    b.Property<int>("Stock")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("STOCK");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("PRODUCTSKUS", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EXPECTEDDATE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<string>("Note")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOTE");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ORDERDATE");

                    b.Property<string>("PoCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("POCODE");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("RECEIVEDDATE");

                    b.Property<byte>("Status")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("STATUS");

                    b.Property<int>("StoreId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STOREID");

                    b.Property<int>("SupplierId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SUPPLIERID");

                    b.Property<long>("TotalCost")
                        .HasColumnType("NUMBER(16,0)")
                        .HasColumnName("TOTALCOST");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("SupplierId");

                    b.ToTable("PURCHASEORDERS", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.PurchaseOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<int>("ProductSkuId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUCTSKUID");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PURCHASEORDERID");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITYORDERED");

                    b.Property<int>("QuantityReceived")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITYRECEIVED");

                    b.Property<long>("Subtotal")
                        .HasColumnType("NUMBER(14,0)")
                        .HasColumnName("SUBTOTAL");

                    b.Property<long>("UnitCost")
                        .HasColumnType("NUMBER(12,0)")
                        .HasColumnName("UNITCOST");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.HasKey("Id");

                    b.HasIndex("ProductSkuId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PURCHASEORDERDETAILS", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.ReturnRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<int>("OrderId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORDERID");

                    b.Property<int?>("OrderId1")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("REASON");

                    b.Property<long>("RefundAmount")
                        .HasColumnType("NUMBER(12,0)")
                        .HasColumnName("REFUNDAMOUNT");

                    b.Property<byte>("Status")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderId1");

                    b.ToTable("RETURNREQUESTS", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.StockAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<string>("AdjustedByUserId")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ADJUSTEDBYUSERID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<int>("InventoryId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("INVENTORYID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<string>("Note")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOTE");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITYAFTER");

                    b.Property<int>("QuantityBefore")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITYBEFORE");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITYCHANGE");

                    b.Property<byte>("Reason")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("REASON");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("STOCKADJUSTMENTS", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ADDRESS");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("ISACTIVE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MANAGERNAME");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("PHONE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.HasKey("Id");

                    b.ToTable("STORES", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CONTACTPERSON");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("ISACTIVE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LEADTIMEDAYS");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NAME");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("PHONE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.HasKey("Id");

                    b.ToTable("SUPPLIERS", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ADDRESSLINE");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("VARCHAR2(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("FULLNAME");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("ISDEFAULT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("PHONENUMBER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("VARCHAR2(450)")
                        .HasColumnName("USERID");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("UserId");

                    b.ToTable("USERADDRESSES", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CODE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<long>("DiscountAmount")
                        .HasColumnType("NUMBER(12,0)")
                        .HasColumnName("DISCOUNTAMOUNT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EXPIRYDATE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("ISACTIVE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<int>("MaxUsageCount")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MAXUSAGECOUNT");

                    b.Property<long>("MinOrderAmount")
                        .HasColumnType("NUMBER(12,0)")
                        .HasColumnName("MINORDERAMOUNT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.Property<int>("UsedCount")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USEDCOUNT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("VOUCHERS", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(450)")
                        .HasColumnName("ID");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("VARCHAR2(2000)")
                        .HasColumnName("CONCURRENCYSTAMP");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR2(256)")
                        .HasColumnName("NAME");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR2(256)")
                        .HasColumnName("NORMALIZEDNAME");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("\"NORMALIZEDNAME\" IS NOT NULL");

                    b.ToTable("ASPNETROLES", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLAIMTYPE");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLAIMVALUE");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(450)")
                        .HasColumnName("ROLEID");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("ASPNETROLECLAIMS", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "HILOSEQUENCE");

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLAIMTYPE");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CLAIMVALUE");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(450)")
                        .HasColumnName("USERID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ASPNETUSERCLAIMS", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)")
                        .HasColumnName("LOGINPROVIDER");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)")
                        .HasColumnName("PROVIDERKEY");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PROVIDERDISPLAYNAME");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(450)")
                        .HasColumnName("USERID");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("ASPNETUSERLOGINS", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("VARCHAR2(450)")
                        .HasColumnName("USERID");

                    b.Property<string>("RoleId")
                        .HasColumnType("VARCHAR2(450)")
                        .HasColumnName("ROLEID");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("ASPNETUSERROLES", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("VARCHAR2(450)")
                        .HasColumnName("USERID");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)")
                        .HasColumnName("LOGINPROVIDER");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)")
                        .HasColumnName("NAME");

                    b.Property<string>("Value")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("VALUE");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("ASPNETUSERTOKENS", (string)null);
                });

            modelBuilder.Entity("FashionStoreIS.Models.Category", b =>
                {
                    b.HasOne("FashionStoreIS.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .HasConstraintName("FK_CAT_PARENT");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("FashionStoreIS.Models.Customer", b =>
                {
                    b.HasOne("FashionStoreIS.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("FashionStoreIS.Models.Customer", "UserId")
                        .HasConstraintName("FK_CUST_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FashionStoreIS.Models.Employee", b =>
                {
                    b.HasOne("FashionStoreIS.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EMP_STORE");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("FashionStoreIS.Models.Inventory", b =>
                {
                    b.HasOne("FashionStoreIS.Models.ProductSku", "ProductSku")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductSkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_INV_SKU");

                    b.HasOne("FashionStoreIS.Models.Store", "Store")
                        .WithMany("Inventories")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_INV_STORE");

                    b.Navigation("ProductSku");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("FashionStoreIS.Models.LoyaltyTransaction", b =>
                {
                    b.HasOne("FashionStoreIS.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LT_CUST");

                    b.HasOne("FashionStoreIS.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FashionStoreIS.Models.Notification", b =>
                {
                    b.HasOne("FashionStoreIS.Models.ApplicationUser", null)
                        .WithMany("Notifications")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("FashionStoreIS.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NOTIF_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FashionStoreIS.Models.Order", b =>
                {
                    b.HasOne("FashionStoreIS.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FashionStoreIS.Models.Store", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ORD_STORE");

                    b.HasOne("FashionStoreIS.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FashionStoreIS.Models.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Store");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("FashionStoreIS.Models.OrderDetail", b =>
                {
                    b.HasOne("FashionStoreIS.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OD_ORD");

                    b.HasOne("FashionStoreIS.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FashionStoreIS.Models.ProductSku", "ProductSku")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductSkuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductSku");
                });

            modelBuilder.Entity("FashionStoreIS.Models.Product", b =>
                {
                    b.HasOne("FashionStoreIS.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_PROD_CAT");

                    b.HasOne("FashionStoreIS.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PROD_SUP");

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("FashionStoreIS.Models.ProductImage", b =>
                {
                    b.HasOne("FashionStoreIS.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FashionStoreIS.Models.ProductSku", b =>
                {
                    b.HasOne("FashionStoreIS.Models.Product", "Product")
                        .WithMany("Skus")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SKU_PROD");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FashionStoreIS.Models.PurchaseOrder", b =>
                {
                    b.HasOne("FashionStoreIS.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PO_STORE");

                    b.HasOne("FashionStoreIS.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PO_SUP");

                    b.Navigation("Store");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("FashionStoreIS.Models.PurchaseOrderDetail", b =>
                {
                    b.HasOne("FashionStoreIS.Models.ProductSku", "ProductSku")
                        .WithMany()
                        .HasForeignKey("ProductSkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_POD_SKU");

                    b.HasOne("FashionStoreIS.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Details")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_POD_PO");

                    b.Navigation("ProductSku");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("FashionStoreIS.Models.ReturnRequest", b =>
                {
                    b.HasOne("FashionStoreIS.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RR_ORDER");

                    b.HasOne("FashionStoreIS.Models.Order", null)
                        .WithMany("ReturnRequests")
                        .HasForeignKey("OrderId1");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FashionStoreIS.Models.StockAdjustment", b =>
                {
                    b.HasOne("FashionStoreIS.Models.Inventory", "Inventory")
                        .WithMany("StockAdjustments")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SA_INV");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("FashionStoreIS.Models.UserAddress", b =>
                {
                    b.HasOne("FashionStoreIS.Models.ApplicationUser", null)
                        .WithMany("Addresses")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("FashionStoreIS.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UA_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FashionStoreIS.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FashionStoreIS.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionStoreIS.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FashionStoreIS.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FashionStoreIS.Models.ApplicationUser", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FashionStoreIS.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("FashionStoreIS.Models.Inventory", b =>
                {
                    b.Navigation("StockAdjustments");
                });

            modelBuilder.Entity("FashionStoreIS.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("ReturnRequests");
                });

            modelBuilder.Entity("FashionStoreIS.Models.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Skus");
                });

            modelBuilder.Entity("FashionStoreIS.Models.ProductSku", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("FashionStoreIS.Models.PurchaseOrder", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("FashionStoreIS.Models.Store", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FashionStoreIS.Models.Supplier", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
